[workspace]

members = [
  "core-impl",
  "dcb-rs",
  "dcb-macros",
  "tools/dcb-bytes",
  "tools/dcb-drv",
  "tools/dcb-mkdrv",
  "tools/dcb-undrv",
  "tools/dcb-cdrom-xa",
  "tools/dcb-unbin",
]

[patch."https://github.com/Zenithsiz/zutil"]
zutil = {path = "../zutil"}
