//! Partner parts

// Imports
use crate::{PsxStr, PartnerPart, PARTNER_PART_LEVELS, PARTNER_PART_DESCRIPTIONS, util};

/// Base address for the names
const NAME_BASE_ADDR: u32 = 0x801df034;


// Partner part descriptions
// TODO: Automate the psx string length, somehow?
util::decl_static! {
	"dylib.evoseg",
	pub static DYLIB_EVOSEG_PARTNER_PART_000: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[000]);
	pub static DYLIB_EVOSEG_PARTNER_PART_001: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[001]);
	pub static DYLIB_EVOSEG_PARTNER_PART_002: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[002]);
	pub static DYLIB_EVOSEG_PARTNER_PART_003: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[003]);
	pub static DYLIB_EVOSEG_PARTNER_PART_004: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[004]);
	pub static DYLIB_EVOSEG_PARTNER_PART_005: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[005]);
	pub static DYLIB_EVOSEG_PARTNER_PART_006: PsxStr<8> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[006]);
	pub static DYLIB_EVOSEG_PARTNER_PART_007: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[007]);
	pub static DYLIB_EVOSEG_PARTNER_PART_008: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[008]);
	pub static DYLIB_EVOSEG_PARTNER_PART_009: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[009]);
	pub static DYLIB_EVOSEG_PARTNER_PART_010: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[010]);
	pub static DYLIB_EVOSEG_PARTNER_PART_011: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[011]);
	pub static DYLIB_EVOSEG_PARTNER_PART_012: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[012]);
	pub static DYLIB_EVOSEG_PARTNER_PART_013: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[013]);
	pub static DYLIB_EVOSEG_PARTNER_PART_014: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[014]);
	pub static DYLIB_EVOSEG_PARTNER_PART_015: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[015]);
	pub static DYLIB_EVOSEG_PARTNER_PART_016: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[016]);
	pub static DYLIB_EVOSEG_PARTNER_PART_017: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[017]);
	pub static DYLIB_EVOSEG_PARTNER_PART_018: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[018]);
	pub static DYLIB_EVOSEG_PARTNER_PART_019: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[019]);
	pub static DYLIB_EVOSEG_PARTNER_PART_020: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[020]);
	pub static DYLIB_EVOSEG_PARTNER_PART_021: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[021]);
	pub static DYLIB_EVOSEG_PARTNER_PART_022: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[022]);
	pub static DYLIB_EVOSEG_PARTNER_PART_023: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[023]);
	pub static DYLIB_EVOSEG_PARTNER_PART_024: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[024]);
	pub static DYLIB_EVOSEG_PARTNER_PART_025: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[025]);
	pub static DYLIB_EVOSEG_PARTNER_PART_026: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[026]);
	pub static DYLIB_EVOSEG_PARTNER_PART_027: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[027]);
	pub static DYLIB_EVOSEG_PARTNER_PART_028: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[028]);
	pub static DYLIB_EVOSEG_PARTNER_PART_029: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[029]);
	pub static DYLIB_EVOSEG_PARTNER_PART_030: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[030]);
	pub static DYLIB_EVOSEG_PARTNER_PART_031: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[031]);
	pub static DYLIB_EVOSEG_PARTNER_PART_032: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[032]);
	pub static DYLIB_EVOSEG_PARTNER_PART_033: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[033]);
	pub static DYLIB_EVOSEG_PARTNER_PART_034: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[034]);
	pub static DYLIB_EVOSEG_PARTNER_PART_035: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[035]);
	pub static DYLIB_EVOSEG_PARTNER_PART_036: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[036]);
	pub static DYLIB_EVOSEG_PARTNER_PART_037: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[037]);
	pub static DYLIB_EVOSEG_PARTNER_PART_038: PsxStr<16> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[038]);
	pub static DYLIB_EVOSEG_PARTNER_PART_039: PsxStr<16> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[039]);
	pub static DYLIB_EVOSEG_PARTNER_PART_040: PsxStr<16> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[040]);
	pub static DYLIB_EVOSEG_PARTNER_PART_041: PsxStr<24> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[041]);
	pub static DYLIB_EVOSEG_PARTNER_PART_042: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[042]);
	pub static DYLIB_EVOSEG_PARTNER_PART_043: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[043]);
	pub static DYLIB_EVOSEG_PARTNER_PART_044: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[044]);
	pub static DYLIB_EVOSEG_PARTNER_PART_045: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[045]);
	pub static DYLIB_EVOSEG_PARTNER_PART_046: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[046]);
	pub static DYLIB_EVOSEG_PARTNER_PART_047: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[047]);
	pub static DYLIB_EVOSEG_PARTNER_PART_048: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[048]);
	pub static DYLIB_EVOSEG_PARTNER_PART_049: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[049]);
	pub static DYLIB_EVOSEG_PARTNER_PART_050: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[050]);
	pub static DYLIB_EVOSEG_PARTNER_PART_051: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[051]);
	pub static DYLIB_EVOSEG_PARTNER_PART_052: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[052]);
	pub static DYLIB_EVOSEG_PARTNER_PART_053: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[053]);
	pub static DYLIB_EVOSEG_PARTNER_PART_054: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[054]);
	pub static DYLIB_EVOSEG_PARTNER_PART_055: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[055]);
	pub static DYLIB_EVOSEG_PARTNER_PART_056: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[056]);
	pub static DYLIB_EVOSEG_PARTNER_PART_057: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[057]);
	pub static DYLIB_EVOSEG_PARTNER_PART_058: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[058]);
	pub static DYLIB_EVOSEG_PARTNER_PART_059: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[059]);
	pub static DYLIB_EVOSEG_PARTNER_PART_060: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[060]);
	pub static DYLIB_EVOSEG_PARTNER_PART_061: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[061]);
	pub static DYLIB_EVOSEG_PARTNER_PART_062: PsxStr<16> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[062]);
	pub static DYLIB_EVOSEG_PARTNER_PART_063: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[063]);
	pub static DYLIB_EVOSEG_PARTNER_PART_064: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[064]);
	pub static DYLIB_EVOSEG_PARTNER_PART_065: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[065]);
	pub static DYLIB_EVOSEG_PARTNER_PART_066: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[066]);
	pub static DYLIB_EVOSEG_PARTNER_PART_067: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[067]);
	pub static DYLIB_EVOSEG_PARTNER_PART_068: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[068]);
	pub static DYLIB_EVOSEG_PARTNER_PART_069: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[069]);
	pub static DYLIB_EVOSEG_PARTNER_PART_070: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[070]);
	pub static DYLIB_EVOSEG_PARTNER_PART_071: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[071]);
	pub static DYLIB_EVOSEG_PARTNER_PART_072: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[072]);
	pub static DYLIB_EVOSEG_PARTNER_PART_073: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[073]);
	pub static DYLIB_EVOSEG_PARTNER_PART_074: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[074]);
	pub static DYLIB_EVOSEG_PARTNER_PART_075: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[075]);
	pub static DYLIB_EVOSEG_PARTNER_PART_076: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[076]);
	pub static DYLIB_EVOSEG_PARTNER_PART_077: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[077]);
	pub static DYLIB_EVOSEG_PARTNER_PART_078: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[078]);
	pub static DYLIB_EVOSEG_PARTNER_PART_079: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[079]);
	pub static DYLIB_EVOSEG_PARTNER_PART_080: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[080]);
	pub static DYLIB_EVOSEG_PARTNER_PART_081: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[081]);
	pub static DYLIB_EVOSEG_PARTNER_PART_082: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[082]);
	pub static DYLIB_EVOSEG_PARTNER_PART_083: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[083]);
	pub static DYLIB_EVOSEG_PARTNER_PART_084: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[084]);
	pub static DYLIB_EVOSEG_PARTNER_PART_085: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[085]);
	pub static DYLIB_EVOSEG_PARTNER_PART_086: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[086]);
	pub static DYLIB_EVOSEG_PARTNER_PART_087: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[087]);
	pub static DYLIB_EVOSEG_PARTNER_PART_088: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[088]);
	pub static DYLIB_EVOSEG_PARTNER_PART_089: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[089]);
	pub static DYLIB_EVOSEG_PARTNER_PART_090: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[090]);
	pub static DYLIB_EVOSEG_PARTNER_PART_091: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[091]);
	pub static DYLIB_EVOSEG_PARTNER_PART_092: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[092]);
	pub static DYLIB_EVOSEG_PARTNER_PART_093: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[093]);
	pub static DYLIB_EVOSEG_PARTNER_PART_094: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[094]);
	pub static DYLIB_EVOSEG_PARTNER_PART_095: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[095]);
	pub static DYLIB_EVOSEG_PARTNER_PART_096: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[096]);
	pub static DYLIB_EVOSEG_PARTNER_PART_097: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[097]);
	pub static DYLIB_EVOSEG_PARTNER_PART_098: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[098]);
	pub static DYLIB_EVOSEG_PARTNER_PART_099: PsxStr<28> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[099]);
	pub static DYLIB_EVOSEG_PARTNER_PART_100: PsxStr<20> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[100]);
	pub static DYLIB_EVOSEG_PARTNER_PART_101: PsxStr<20> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[101]);
	pub static DYLIB_EVOSEG_PARTNER_PART_102: PsxStr<20> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[102]);
	pub static DYLIB_EVOSEG_PARTNER_PART_103: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[103]);
	pub static DYLIB_EVOSEG_PARTNER_PART_104: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[104]);
	pub static DYLIB_EVOSEG_PARTNER_PART_105: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[105]);
	pub static DYLIB_EVOSEG_PARTNER_PART_106: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[106]);
	pub static DYLIB_EVOSEG_PARTNER_PART_107: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[107]);
	pub static DYLIB_EVOSEG_PARTNER_PART_108: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[108]);
	pub static DYLIB_EVOSEG_PARTNER_PART_109: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[109]);
	pub static DYLIB_EVOSEG_PARTNER_PART_110: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[110]);
	pub static DYLIB_EVOSEG_PARTNER_PART_111: PsxStr<36> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[111]);
	pub static DYLIB_EVOSEG_PARTNER_PART_112: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[112]);
	pub static DYLIB_EVOSEG_PARTNER_PART_113: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[113]);
	pub static DYLIB_EVOSEG_PARTNER_PART_114: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[114]);
	pub static DYLIB_EVOSEG_PARTNER_PART_115: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[115]);
	pub static DYLIB_EVOSEG_PARTNER_PART_116: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[116]);
	pub static DYLIB_EVOSEG_PARTNER_PART_117: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[117]);
	pub static DYLIB_EVOSEG_PARTNER_PART_118: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[118]);
	pub static DYLIB_EVOSEG_PARTNER_PART_119: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[119]);
	pub static DYLIB_EVOSEG_PARTNER_PART_120: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[120]);
	pub static DYLIB_EVOSEG_PARTNER_PART_121: PsxStr<44> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[121]);
	pub static DYLIB_EVOSEG_PARTNER_PART_122: PsxStr<44> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[122]);
	pub static DYLIB_EVOSEG_PARTNER_PART_123: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[123]);
	pub static DYLIB_EVOSEG_PARTNER_PART_124: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[124]);
	pub static DYLIB_EVOSEG_PARTNER_PART_125: PsxStr<32> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[125]);
	pub static DYLIB_EVOSEG_PARTNER_PART_126: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[126]);
	pub static DYLIB_EVOSEG_PARTNER_PART_127: PsxStr<40> = PsxStr::from_str(PARTNER_PART_DESCRIPTIONS[127]);
}


/// Partner parts
#[no_mangle]
#[link_section = "dylib.evoseg.DYLIB_EVOSEG_PARTNER_PARTS"]
#[rustfmt::skip]
static DYLIB_EVOSEG_PARTNER_PARTS: [PartnerPart; 128] = [
	PartnerPart::new(NAME_BASE_ADDR        , PARTNER_PART_LEVELS[000]),
	PartnerPart::new(NAME_BASE_ADDR - 0x8  , PARTNER_PART_LEVELS[001]),
	PartnerPart::new(NAME_BASE_ADDR - 0x10 , PARTNER_PART_LEVELS[002]),
	PartnerPart::new(NAME_BASE_ADDR - 0x18 , PARTNER_PART_LEVELS[003]),
	PartnerPart::new(NAME_BASE_ADDR - 0x20 , PARTNER_PART_LEVELS[004]),
	PartnerPart::new(NAME_BASE_ADDR - 0x28 , PARTNER_PART_LEVELS[005]),
	PartnerPart::new(NAME_BASE_ADDR - 0x30 , PARTNER_PART_LEVELS[006]),
	PartnerPart::new(NAME_BASE_ADDR - 0x48 , PARTNER_PART_LEVELS[007]),
	PartnerPart::new(NAME_BASE_ADDR - 0x60 , PARTNER_PART_LEVELS[008]),
	PartnerPart::new(NAME_BASE_ADDR - 0x78 , PARTNER_PART_LEVELS[009]),
	PartnerPart::new(NAME_BASE_ADDR - 0x90 , PARTNER_PART_LEVELS[010]),
	PartnerPart::new(NAME_BASE_ADDR - 0xa8 , PARTNER_PART_LEVELS[011]),
	PartnerPart::new(NAME_BASE_ADDR - 0xc0 , PARTNER_PART_LEVELS[012]),
	PartnerPart::new(NAME_BASE_ADDR - 0xd8 , PARTNER_PART_LEVELS[013]),
	PartnerPart::new(NAME_BASE_ADDR - 0xf0 , PARTNER_PART_LEVELS[014]),
	PartnerPart::new(NAME_BASE_ADDR - 0x108, PARTNER_PART_LEVELS[015]),
	PartnerPart::new(NAME_BASE_ADDR - 0x120, PARTNER_PART_LEVELS[016]),
	PartnerPart::new(NAME_BASE_ADDR - 0x138, PARTNER_PART_LEVELS[017]),
	PartnerPart::new(NAME_BASE_ADDR - 0x150, PARTNER_PART_LEVELS[018]),
	PartnerPart::new(NAME_BASE_ADDR - 0x168, PARTNER_PART_LEVELS[019]),
	PartnerPart::new(NAME_BASE_ADDR - 0x180, PARTNER_PART_LEVELS[020]),
	PartnerPart::new(NAME_BASE_ADDR - 0x198, PARTNER_PART_LEVELS[021]),
	PartnerPart::new(NAME_BASE_ADDR - 0x1b0, PARTNER_PART_LEVELS[022]),
	PartnerPart::new(NAME_BASE_ADDR - 0x1c8, PARTNER_PART_LEVELS[023]),
	PartnerPart::new(NAME_BASE_ADDR - 0x1ec, PARTNER_PART_LEVELS[024]),
	PartnerPart::new(NAME_BASE_ADDR - 0x210, PARTNER_PART_LEVELS[025]),
	PartnerPart::new(NAME_BASE_ADDR - 0x234, PARTNER_PART_LEVELS[026]),
	PartnerPart::new(NAME_BASE_ADDR - 0x258, PARTNER_PART_LEVELS[027]),
	PartnerPart::new(NAME_BASE_ADDR - 0x27c, PARTNER_PART_LEVELS[028]),
	PartnerPart::new(NAME_BASE_ADDR - 0x2a0, PARTNER_PART_LEVELS[029]),
	PartnerPart::new(NAME_BASE_ADDR - 0x2c8, PARTNER_PART_LEVELS[030]),
	PartnerPart::new(NAME_BASE_ADDR - 0x2f0, PARTNER_PART_LEVELS[031]),
	PartnerPart::new(NAME_BASE_ADDR - 0x318, PARTNER_PART_LEVELS[032]),
	PartnerPart::new(NAME_BASE_ADDR - 0x340, PARTNER_PART_LEVELS[033]),
	PartnerPart::new(NAME_BASE_ADDR - 0x368, PARTNER_PART_LEVELS[034]),
	PartnerPart::new(NAME_BASE_ADDR - 0x38c, PARTNER_PART_LEVELS[035]),
	PartnerPart::new(NAME_BASE_ADDR - 0x3b4, PARTNER_PART_LEVELS[036]),
	PartnerPart::new(NAME_BASE_ADDR - 0x3d8, PARTNER_PART_LEVELS[037]),
	PartnerPart::new(NAME_BASE_ADDR - 0x3e8, PARTNER_PART_LEVELS[038]),
	PartnerPart::new(NAME_BASE_ADDR - 0x3f8, PARTNER_PART_LEVELS[039]),
	PartnerPart::new(NAME_BASE_ADDR - 0x408, PARTNER_PART_LEVELS[040]),
	PartnerPart::new(NAME_BASE_ADDR - 0x420, PARTNER_PART_LEVELS[041]),
	PartnerPart::new(NAME_BASE_ADDR - 0x43c, PARTNER_PART_LEVELS[042]),
	PartnerPart::new(NAME_BASE_ADDR - 0x458, PARTNER_PART_LEVELS[043]),
	PartnerPart::new(NAME_BASE_ADDR - 0x474, PARTNER_PART_LEVELS[044]),
	PartnerPart::new(NAME_BASE_ADDR - 0x490, PARTNER_PART_LEVELS[045]),
	PartnerPart::new(NAME_BASE_ADDR - 0x4b0, PARTNER_PART_LEVELS[046]),
	PartnerPart::new(NAME_BASE_ADDR - 0x4d0, PARTNER_PART_LEVELS[047]),
	PartnerPart::new(NAME_BASE_ADDR - 0x4f0, PARTNER_PART_LEVELS[048]),
	PartnerPart::new(NAME_BASE_ADDR - 0x510, PARTNER_PART_LEVELS[049]),
	PartnerPart::new(NAME_BASE_ADDR - 0x530, PARTNER_PART_LEVELS[050]),
	PartnerPart::new(NAME_BASE_ADDR - 0x550, PARTNER_PART_LEVELS[051]),
	PartnerPart::new(NAME_BASE_ADDR - 0x570, PARTNER_PART_LEVELS[052]),
	PartnerPart::new(NAME_BASE_ADDR - 0x590, PARTNER_PART_LEVELS[053]),
	PartnerPart::new(NAME_BASE_ADDR - 0x5b0, PARTNER_PART_LEVELS[054]),
	PartnerPart::new(NAME_BASE_ADDR - 0x5d0, PARTNER_PART_LEVELS[055]),
	PartnerPart::new(NAME_BASE_ADDR - 0x5f0, PARTNER_PART_LEVELS[056]),
	PartnerPart::new(NAME_BASE_ADDR - 0x610, PARTNER_PART_LEVELS[057]),
	PartnerPart::new(NAME_BASE_ADDR - 0x630, PARTNER_PART_LEVELS[058]),
	PartnerPart::new(NAME_BASE_ADDR - 0x650, PARTNER_PART_LEVELS[059]),
	PartnerPart::new(NAME_BASE_ADDR - 0x670, PARTNER_PART_LEVELS[060]),
	PartnerPart::new(NAME_BASE_ADDR - 0x694, PARTNER_PART_LEVELS[061]),
	PartnerPart::new(NAME_BASE_ADDR - 0x6a4, PARTNER_PART_LEVELS[062]),
	PartnerPart::new(NAME_BASE_ADDR - 0x6c0, PARTNER_PART_LEVELS[063]),
	PartnerPart::new(NAME_BASE_ADDR - 0x6e8, PARTNER_PART_LEVELS[064]),
	PartnerPart::new(NAME_BASE_ADDR - 0x710, PARTNER_PART_LEVELS[065]),
	PartnerPart::new(NAME_BASE_ADDR - 0x738, PARTNER_PART_LEVELS[066]),
	PartnerPart::new(NAME_BASE_ADDR - 0x758, PARTNER_PART_LEVELS[067]),
	PartnerPart::new(NAME_BASE_ADDR - 0x778, PARTNER_PART_LEVELS[068]),
	PartnerPart::new(NAME_BASE_ADDR - 0x798, PARTNER_PART_LEVELS[069]),
	PartnerPart::new(NAME_BASE_ADDR - 0x7c0, PARTNER_PART_LEVELS[070]),
	PartnerPart::new(NAME_BASE_ADDR - 0x7e8, PARTNER_PART_LEVELS[071]),
	PartnerPart::new(NAME_BASE_ADDR - 0x810, PARTNER_PART_LEVELS[072]),
	PartnerPart::new(NAME_BASE_ADDR - 0x838, PARTNER_PART_LEVELS[073]),
	PartnerPart::new(NAME_BASE_ADDR - 0x860, PARTNER_PART_LEVELS[074]),
	PartnerPart::new(NAME_BASE_ADDR - 0x888, PARTNER_PART_LEVELS[075]),
	PartnerPart::new(NAME_BASE_ADDR - 0x8b0, PARTNER_PART_LEVELS[076]),
	PartnerPart::new(NAME_BASE_ADDR - 0x8d8, PARTNER_PART_LEVELS[077]),
	PartnerPart::new(NAME_BASE_ADDR - 0x900, PARTNER_PART_LEVELS[078]),
	PartnerPart::new(NAME_BASE_ADDR - 0x928, PARTNER_PART_LEVELS[079]),
	PartnerPart::new(NAME_BASE_ADDR - 0x948, PARTNER_PART_LEVELS[080]),
	PartnerPart::new(NAME_BASE_ADDR - 0x968, PARTNER_PART_LEVELS[081]),
	PartnerPart::new(NAME_BASE_ADDR - 0x988, PARTNER_PART_LEVELS[082]),
	PartnerPart::new(NAME_BASE_ADDR - 0x9a8, PARTNER_PART_LEVELS[083]),
	PartnerPart::new(NAME_BASE_ADDR - 0x9c8, PARTNER_PART_LEVELS[084]),
	PartnerPart::new(NAME_BASE_ADDR - 0x9ec, PARTNER_PART_LEVELS[085]),
	PartnerPart::new(NAME_BASE_ADDR - 0xa0c, PARTNER_PART_LEVELS[086]),
	PartnerPart::new(NAME_BASE_ADDR - 0xa30, PARTNER_PART_LEVELS[087]),
	PartnerPart::new(NAME_BASE_ADDR - 0xa54, PARTNER_PART_LEVELS[088]),
	PartnerPart::new(NAME_BASE_ADDR - 0xa78, PARTNER_PART_LEVELS[089]),
	PartnerPart::new(NAME_BASE_ADDR - 0xa9c, PARTNER_PART_LEVELS[090]),
	PartnerPart::new(NAME_BASE_ADDR - 0xac0, PARTNER_PART_LEVELS[091]),
	PartnerPart::new(NAME_BASE_ADDR - 0xae4, PARTNER_PART_LEVELS[092]),
	PartnerPart::new(NAME_BASE_ADDR - 0xb08, PARTNER_PART_LEVELS[093]),
	PartnerPart::new(NAME_BASE_ADDR - 0xb2c, PARTNER_PART_LEVELS[094]),
	PartnerPart::new(NAME_BASE_ADDR - 0xb50, PARTNER_PART_LEVELS[095]),
	PartnerPart::new(NAME_BASE_ADDR - 0xb6c, PARTNER_PART_LEVELS[096]),
	PartnerPart::new(NAME_BASE_ADDR - 0xb88, PARTNER_PART_LEVELS[097]),
	PartnerPart::new(NAME_BASE_ADDR - 0xba4, PARTNER_PART_LEVELS[098]),
	PartnerPart::new(NAME_BASE_ADDR - 0xbc0, PARTNER_PART_LEVELS[099]),
	PartnerPart::new(NAME_BASE_ADDR - 0xbd4, PARTNER_PART_LEVELS[100]),
	PartnerPart::new(NAME_BASE_ADDR - 0xbe8, PARTNER_PART_LEVELS[101]),
	PartnerPart::new(NAME_BASE_ADDR - 0xbfc, PARTNER_PART_LEVELS[102]),
	PartnerPart::new(NAME_BASE_ADDR - 0xc24, PARTNER_PART_LEVELS[103]),
	PartnerPart::new(NAME_BASE_ADDR - 0xc4c, PARTNER_PART_LEVELS[104]),
	PartnerPart::new(NAME_BASE_ADDR - 0xc70, PARTNER_PART_LEVELS[105]),
	PartnerPart::new(NAME_BASE_ADDR - 0xc94, PARTNER_PART_LEVELS[106]),
	PartnerPart::new(NAME_BASE_ADDR - 0xcbc, PARTNER_PART_LEVELS[107]),
	PartnerPart::new(NAME_BASE_ADDR - 0xce4, PARTNER_PART_LEVELS[108]),
	PartnerPart::new(NAME_BASE_ADDR - 0xd0c, PARTNER_PART_LEVELS[109]),
	PartnerPart::new(NAME_BASE_ADDR - 0xd2c, PARTNER_PART_LEVELS[110]),
	PartnerPart::new(NAME_BASE_ADDR - 0xd50, PARTNER_PART_LEVELS[111]),
	PartnerPart::new(NAME_BASE_ADDR - 0xd78, PARTNER_PART_LEVELS[112]),
	PartnerPart::new(NAME_BASE_ADDR - 0xda0, PARTNER_PART_LEVELS[113]),
	PartnerPart::new(NAME_BASE_ADDR - 0xdc8, PARTNER_PART_LEVELS[114]),
	PartnerPart::new(NAME_BASE_ADDR - 0xdf0, PARTNER_PART_LEVELS[115]),
	PartnerPart::new(NAME_BASE_ADDR - 0xe18, PARTNER_PART_LEVELS[116]),
	PartnerPart::new(NAME_BASE_ADDR - 0xe40, PARTNER_PART_LEVELS[117]),
	PartnerPart::new(NAME_BASE_ADDR - 0xe60, PARTNER_PART_LEVELS[118]),
	PartnerPart::new(NAME_BASE_ADDR - 0xe80, PARTNER_PART_LEVELS[119]),
	PartnerPart::new(NAME_BASE_ADDR - 0xea8, PARTNER_PART_LEVELS[120]),
	PartnerPart::new(NAME_BASE_ADDR - 0xed4, PARTNER_PART_LEVELS[121]),
	PartnerPart::new(NAME_BASE_ADDR - 0xf00, PARTNER_PART_LEVELS[122]),
	PartnerPart::new(NAME_BASE_ADDR - 0xf20, PARTNER_PART_LEVELS[123]),
	PartnerPart::new(NAME_BASE_ADDR - 0xf40, PARTNER_PART_LEVELS[124]),
	PartnerPart::new(NAME_BASE_ADDR - 0xf60, PARTNER_PART_LEVELS[125]),
	PartnerPart::new(NAME_BASE_ADDR - 0xf88, PARTNER_PART_LEVELS[126]),
	PartnerPart::new(NAME_BASE_ADDR - 0xfb0, PARTNER_PART_LEVELS[127]),
];
