# Note: This file is for IDE completion only, we don't build using it.

[package]
edition = "2021"
name = "dcb"
version = "0.1.0"

[dependencies]

core = {path = "../core"}
dcb-macros = {path = "../dcb-macros"}
