[package]
edition = "2021"
name = "dcb-util"
version = "0.1.0"

[dependencies]

# Dcb
dcb-logger = {path = "../dcb-logger"}

# Logging
tracing = "0.1.37"

# Error handling
anyhow = "1.0.65"

# Serde
serde = {version = "1.0.145", features = ["derive"]}
