[workspace]

members = [
  # Libraries
  "dcb-bytes",
  "dcb-drv",
  "dcb-pak",
  "dcb-cdrom-xa", #
  # Binaries
  "dcb-mkdrv",
  "dcb-mkdrv-deps",
  "dcb-undrv",
  "dcb-unbin",
  "dcb-unpak",
  "dcb-mkpak",
]

[patch."https://github.com/Zenithsiz/zutil"]
zutil = {path = "../../zutil"}
