[workspace]

members = [
  "dcb-bytes",
  "dcb-drv",
  "dcb-mkdrv",
  "dcb-mkdrv-deps",
  "dcb-undrv",
  "dcb-cdrom-xa",
  "dcb-unbin",
  "dcb-build",
]

[patch."https://github.com/Zenithsiz/zutil"]
zutil = {path = "../../zutil"}
