[workspace]

members = [
  # Libraries
  "dcb-bytes",
  "dcb-drv",
  "dcb-cdrom-xa", #
  ### Binaries
  "dcb-mkdrv",
  "dcb-mkdrv-deps", # TODO: Remove
  "dcb-undrv",
  "dcb-unbin",
  "dcb-build",
]

[patch."https://github.com/Zenithsiz/zutil"]
zutil = {path = "../../zutil"}
