[package]
edition = "2021"
name = "dcb-mkdrv"
version = "0.1.0"

[dependencies]
# Dcb
dcb-drv = {path = "../dcb-drv"}
zutil = {git = "https://github.com/Zenithsiz/zutil", rev = "2a029369ac5aa4e7dbd6f6afb78ae419ee18666f"}

# Util
chrono = "0.4.19"
itertools = "0.10.0"
size_format = "1.0.2"

# Cmd
clap = "2.33.3"

# Logging
log = "0.4.13"
simplelog = "0.9.0"

# Error handling
anyhow = "1.0.38"
thiserror = "1.0.23"
